import { escapeHtml as e, safeHref, safeEmail, sortPublications, splitPeople } from './core.mjs';

const link = (url, label, cls = 'text-link') => url ? `<a class="${cls}" href="${e(url)}">${e(label)} <span aria-hidden="true">↗</span></a>` : '';
const paras = text => String(text || '').split(/\n\s*\n/).filter(Boolean).map(p => `<p>${e(p).replace(/\n/g, '<br>')}</p>`).join('');
const empty = (title, description) => `<div class="empty-state"><span class="empty-mark" aria-hidden="true">—</span><h3>${e(title)}</h3><p>${e(description)}</p></div>`;
const heading = (en, ko, description = '') => `<header class="page-heading"><p class="eyebrow">${en}</p><h1>${ko}</h1>${description ? `<p class="intro">${e(description)}</p>` : ''}</header>`;
const roles = { PhD: '박사과정', MS: '석사과정', Integrated: '석·박사 통합과정', Undergraduate: '학부연구생', Researcher: '연구원' };

function portrait(p, big = false) {
  const photo = safeHref(p.photo);
  const initials = (p.nameEn || p.name || '').split(/\s+/).map(s => s[0]).slice(0,2).join('');
  return photo ? `<img class="portrait ${big ? 'portrait-large' : ''}" src="${e(photo)}" alt="${e(p.name)}" loading="lazy" width="320" height="360">` : `<div class="portrait monogram ${big ? 'portrait-large' : ''}" aria-hidden="true"><span>${e(initials)}</span><small>${big ? 'PRINCIPAL INVESTIGATOR' : 'CSP LAB'}</small></div>`;
}
function researchCards(items, detail = false) {
  return `<div class="research-grid">${items.map((r, i) => `<article class="research-card"><div class="card-top"><span class="ordinal">${String(i+1).padStart(2,'0')}</span><span class="small-label">RESEARCH AREA</span></div>${safeHref(r.image) ? `<img class="research-image" src="${e(safeHref(r.image))}" alt="${e(r.title)}" loading="lazy">` : ''}<h${detail ? '2':'3'}>${e(r.title)}</h${detail ? '2':'3'}><p class="english-label" lang="en">${e(r.titleEn)}</p><p>${e(r.summary)}</p>${detail ? `<div class="research-detail">${paras(r.details)}</div>` : ''}</article>`).join('')}</div>`;
}
function publication(p) {
  const doi = String(p.doi || '').replace(/^https?:\/\/(dx\.)?doi\.org\//i,'');
  const doiUrl = /^10\.\d{4,9}\/\S+$/.test(doi) ? 'https://doi.org/' + doi : '';
  return `<article class="publication" data-publication data-search="${e(`${p.title} ${p.authors} ${p.venue}`.toLocaleLowerCase())}" data-year="${e(p.year)}" data-type="${e(p.type)}"><div class="publication-meta"><span>${e(p.type)}</span>${p.featured ? '<span class="featured-label">Selected</span>' : ''}</div><h3>${e(p.title)}</h3><p class="authors">${e(p.authors)}</p><p class="venue">${e(p.venue)} · ${e(p.year)}</p><div class="publication-links">${link(doiUrl,'DOI')}${link(safeHref(p.url),'논문 링크')}${link(safeHref(p.pdf),'PDF')}${link(safeHref(p.code),'Code')}</div></article>`;
}
function people(items, alumni = false) {
  return items.length ? `<div class="people-grid">${items.map(p => `<article class="person-card">${portrait(p)}<div class="person-info"><span class="small-label">${e(roles[p.role] || p.role)}</span><h2>${e(p.name)}</h2><p class="english-label" lang="en">${e(p.nameEn)}</p>${p.interests ? `<p>${e(p.interests)}</p>` : ''}${p.startYear || p.endYear ? `<p class="period">${e(p.startYear || '')}${alumni ? ' – ' + e(p.endYear || '') : ' – 현재'}</p>` : ''}${alumni && p.currentPosition ? `<p class="current-position">${e(p.currentPosition)}</p>` : ''}<div class="publication-links">${link(safeEmail(p.email),'Email')}${link(safeHref(p.website),'Website')}</div></div></article>`).join('')}</div>` : empty(alumni ? '졸업생 소개를 준비하고 있습니다' : '구성원 소개를 준비하고 있습니다', alumni ? '연구실과 함께한 졸업생들의 소식을 이곳에 전합니다.' : '함께 연구하는 구성원들의 관심 분야와 활동을 소개할 예정입니다.');
}
export function renderSite(data) {
  const { site: s, professor: p } = data;
  const research = [...data.research].sort((a,b) => Number(a.order || 0) - Number(b.order || 0));
  const pubs = sortPublications(data.publications.map(p => ({...p, year: Number(p.year)})));
  const selected = pubs.filter(p => p.featured).slice(0,3);
  const { current, alumni } = splitPeople(data.people);
  const nav = [['home','Home'],['professor','Professor'],['research','Research'],['publications','Publications'],['people','People'],['alumni','Alumni']];
  const years = [...new Set(pubs.map(p => p.year))];
  const bioList = (name, items) => Array.isArray(items) && items.length ? `<section class="bio-list"><h2>${name}</h2><ul>${items.map(i=>`<li>${e(i)}</li>`).join('')}</ul></section>` : '';
  return `<!doctype html>
<html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${e(s.shortName)} | ${e(s.name)}</title><meta name="description" content="${e(s.description)}"><meta name="theme-color" content="#102f38"><meta property="og:title" content="${e(s.name)}"><meta property="og:description" content="${e(s.description)}"><meta property="og:type" content="website"><link rel="icon" type="image/svg+xml" href="./assets/favicon.svg"><link rel="stylesheet" href="./assets/style.css"><script type="module" src="./assets/app.js"></script></head>
<body><a class="skip-link" href="#main">본문으로 건너뛰기</a><header class="site-header"><a class="brand" href="#home" aria-label="${e(s.shortName)} 홈"><span class="brand-symbol" aria-hidden="true">C<span>·</span></span><span>${e(s.shortName)}<small>CHONNAM NATIONAL UNIVERSITY</small></span></a><button class="menu-toggle" aria-expanded="false" aria-controls="site-nav" hidden>메뉴 <span aria-hidden="true">☰</span></button><nav id="site-nav" aria-label="주 메뉴">${nav.map(([id,label])=>`<a href="#${id}" data-nav="${id}">${label}</a>`).join('')}</nav></header>
<main id="main" tabindex="-1">
<section data-view="home" aria-label="연구실 홈">
<div class="hero"><div class="hero-copy"><p class="eyebrow">CRYPTOGRAPHY & SECURITY</p><p class="affiliation">${e(s.affiliation)}</p><h1>${e(s.headline).replace(/\n/g,'<br>')}</h1><p class="hero-description">${e(s.description)}</p><div class="hero-actions"><a class="button button-dark" href="#research">연구 분야 살펴보기 <span aria-hidden="true">↗</span></a><a class="text-link" href="#professor">교수 소개 <span aria-hidden="true">→</span></a></div></div><aside class="hero-index" aria-label="연구실 소개"><p class="index-label">${e(s.nameEn)}</p><div class="wordmark" aria-hidden="true">CSP<span>LAB<span class="wordmark-dot">.</span></span></div><div class="index-bottom"><span>THEORY<br>TO APPLICATION</span><span>암호의 이론에서<br>보안의 실제까지</span></div></aside></div>
<div class="lab-name-band"><span>${e(s.name)}</span><span lang="en">${e(s.nameEn)}</span></div>
<section class="content-section"><div class="section-heading"><div><p class="eyebrow">OUR RESEARCH</p><h2>우리가 연구하는 것</h2></div><a class="text-link" href="#research">전체 연구 분야 <span aria-hidden="true">→</span></a></div>${researchCards(research)}</section>
<section class="professor-strip"><div><p class="eyebrow">PRINCIPAL INVESTIGATOR</p><h2>${e(p.name)} <span lang="en">${e(p.nameEn)}</span></h2><p>${e(p.affiliation)}</p></div><div><p>${e(p.bio)}</p><a class="text-link" href="#professor">교수 소개 보기 <span aria-hidden="true">→</span></a></div></section>
${pubs.length ? `<section class="content-section"><div class="section-heading"><div><p class="eyebrow">${selected.length ? 'SELECTED':'RECENT'} PUBLICATIONS</p><h2>${selected.length ? '주요':'최근'} 연구 성과</h2></div><a class="text-link" href="#publications">모든 논문 <span aria-hidden="true">→</span></a></div>${(selected.length ? selected : pubs.slice(0,3)).map(publication).join('')}</section>` : ''}
${s.recruiting ? `<section class="recruiting"><div><p class="eyebrow">JOIN OUR LAB</p><h2>함께 질문하고,<br>연구할 동료를 기다립니다.</h2></div><div><p>${e(s.recruitingText)}</p><div class="hero-actions">${link(safeEmail(s.email),'연구실에 문의하기','button button-light')}${link(safeHref(s.recruitingUrl),'모집 공고')}</div></div></section>` : ''}
</section>
<section class="inner-page" data-view="professor" aria-label="교수 소개">${heading('PROFESSOR','교수 소개')}<div class="professor-profile">${portrait(p,true)}<div><p class="eyebrow">${e(p.title)}</p><h2>${e(p.name)}</h2><p class="name-en" lang="en">${e(p.nameEn)}</p><p>${e(p.affiliation)}</p><div class="bio">${paras(p.bio)}</div><dl class="contact-list">${p.email ? `<div><dt>Email</dt><dd>${link(safeEmail(p.email),p.email)}</dd></div>` : ''}${p.phone ? `<div><dt>Office</dt><dd>${e(p.phone)}</dd></div>` : ''}</dl><div class="publication-links">${link(safeHref(p.scholarUrl),'Google Scholar')}${link(safeHref(p.cvUrl),'Curriculum Vitae')}</div></div></div><div class="bio-columns">${bioList('학력 · Education',p.education)}${bioList('경력 · Experience',p.experience)}</div></section>
<section class="inner-page" data-view="research" aria-label="연구 분야">${heading('RESEARCH','연구 분야','공개키암호와 보안 프로토콜을 중심으로, 신뢰와 프라이버시를 위한 기술을 연구합니다.')}${research.length ? researchCards(research,true) : empty('연구 분야를 준비하고 있습니다','연구실의 주요 주제를 이곳에 소개합니다.')}</section>
<section class="inner-page" data-view="publications" aria-label="논문">${heading('PUBLICATIONS','연구 논문','암호학과 보안 연구의 결과를 공유합니다.')}<div class="publication-filters" ${pubs.length ? '' : 'hidden'}><label class="search-label">논문 검색<input type="search" id="publication-search" placeholder="제목, 저자, 학술지로 검색" autocomplete="off"></label><label>연도<select id="publication-year"><option value="">모든 연도</option>${years.map(y=>`<option>${e(y)}</option>`).join('')}</select></label><label>유형<select id="publication-type"><option value="">모든 유형</option><option>Journal</option><option>Conference</option><option>Preprint</option></select></label></div><p class="result-count" id="publication-count" role="status">${pubs.length ? `총 ${pubs.length}편` : ''}</p><div id="publication-results">${years.map(year => `<section class="year-group" data-year-group><h2>${e(year)}</h2><div>${pubs.filter(p=>p.year===year).map(publication).join('')}</div></section>`).join('')}</div><div id="no-results" hidden>${empty('검색 결과가 없습니다','검색어나 연도·유형 조건을 바꿔보세요.')}</div>${!pubs.length ? empty('논문 목록을 준비하고 있습니다','확인된 연구 성과를 정리하여 공개할 예정입니다.') : ''}</section>
<section class="inner-page" data-view="people" aria-label="구성원">${heading('PEOPLE','함께 연구하는 사람들')}<div class="people-tabs"><a class="active" href="#people" aria-current="page">Current Members</a><a href="#alumni">Alumni <span aria-hidden="true">↗</span></a></div>${people(current)}</section>
<section class="inner-page" data-view="alumni" aria-label="졸업생">${heading('ALUMNI','함께한 사람들')}<div class="people-tabs"><a href="#people">Current Members</a><a class="active" href="#alumni" aria-current="page">Alumni</a></div>${people(alumni,true)}</section>
</main><footer class="site-footer"><div><a class="footer-brand" href="#home">${e(s.shortName)}</a><p>${e(s.name)}<br>${e(s.address)}</p></div><div class="footer-contact"><span class="eyebrow">GET IN TOUCH</span>${link(safeEmail(s.email),s.email)}${s.phone ? `<p>${e(s.phone)}</p>` : ''}</div><div class="footer-bottom"><span>© ${new Date().getFullYear()} ${e(s.shortName)}</span><a href="./admin/">사이트 관리</a></div></footer></body></html>`;
}

export function renderAdmin(site) {
  return `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex"><title>사이트 관리 | ${e(site.shortName)}</title><link rel="icon" href="../assets/favicon.svg"><link rel="stylesheet" href="../assets/style.css"></head><body class="admin-body"><header class="admin-header"><a class="footer-brand" href="../">${e(site.shortName)}</a><a class="text-link" href="../">홈페이지로 돌아가기 →</a></header><main class="admin-main"><p class="eyebrow">CONTENT MANAGEMENT</p><h1>연구실의 새로운 소식을<br>간편하게 업데이트하세요.</h1><p class="intro">관리 화면에서 내용을 입력하고 저장하면 홈페이지에 반영됩니다.<br>처음 한 번, GitHub 계정과 편집 도구를 연결해야 합니다.</p><a class="button button-dark" href="https://app.pagescms.org/">Pages CMS 관리 화면 열기 ↗</a><p class="admin-note">로그인한 뒤 <strong>jnu-csplab / labwebsite</strong> 저장소와 <strong>main</strong>을 선택하세요.</p><div class="admin-cards"><article><span class="ordinal">01</span><h2>논문 추가</h2><p>‘연구 논문’에서 항목을 추가하고 제목, 저자, 연도, 학술지와 링크를 입력합니다.</p></article><article><span class="ordinal">02</span><h2>구성원 관리</h2><p>‘구성원·졸업생’에서 사진과 소개를 등록합니다. 상태를 ‘졸업생’으로 바꾸면 Alumni에 표시됩니다.</p></article><article><span class="ordinal">03</span><h2>소개 수정</h2><p>‘연구실 기본 정보’, ‘교수 소개’, ‘연구 분야’에서 문구와 사진을 변경합니다.</p></article></div><section class="setup-box"><h2>처음 연결할 때</h2><ol><li>Pages CMS에서 GitHub 계정으로 로그인합니다.</li><li>연동 안내가 나오면 <strong>labwebsite 저장소만</strong> 선택하여 접근을 허용합니다.</li><li>저장소를 열면 준비된 한국어 항목으로 편집할 수 있습니다.</li><li>변경을 저장하고 <a href="https://github.com/jnu-csplab/labwebsite/actions">배포 진행 상황</a>에서 성공을 확인합니다. 반영에는 잠시 시간이 걸릴 수 있습니다.</li></ol><p>초기 공개에는 저장소의 Pages 설정이 필요합니다. 비공개 저장소의 Pages 제공 여부는 GitHub 요금제에 따라 달라집니다.</p></section><p class="admin-note">이 화면은 관리 도구로 연결하는 안내 페이지입니다. 편집과 저장은 Pages CMS에서 인증한 관리자에게만 허용됩니다.</p></main></body></html>`;
}
